apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#  - capy-controller.Application.yaml
resources:
- ../config/default/
#  - resources/
#  - extra-resources/

patches:
- path: patches/capy-controller-manager.Deployment.yaml
